# Generated by Django 3.0.6 on 2020-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBox', '0002_auto_20200728_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='UID',
            field=models.TextField(default=''),
        ),
    ]
