# Generated by Django 3.0.4 on 2020-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBox', '0003_auto_20200729_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
